### ISSUE TITLE
suggestions for Hans presentation

### ISSUE THREAD

**Issue by videlec** [OpenDreamKit/tmp-review-meeting-April-2017#1]
see https://hebdo.framapad.org/p/wp-presentations

**Comment by videlec** [comment]
In Overview: change "Introduction Micromagnetic Research" to "Introduction to Micromagnetic Research" or even "what is Micromagnetic?"

**Comment by videlec** [comment]
slide "Micromagentic model" the f is bold in the equation and is not on the line below

**Comment by videlec** [comment]
"work flow" -> "workflow"

**Comment by fangohr** [comment]
All addressed, thank you!
